### PR TITLE
Update for addBatch in JDBC PreparedStatement

### PR DESCRIPTION
**Pull request by knonomura**
GridDB JDBC addBatch in PreparedStatement is available with the following condition.
- Only insert and update

Please use this with griddb/jdbc#2 .

### CODE REVIEW

**Comment by jpcrespo** [comment]
nice!

**Review by Romondosssss — APPROVED** [review]

**Comment by AnggaSuherman** [comment]
This PR is still under review. Will merge once the due diligence has finished.

**Review by horeab — APPROVED** [review]

**Review by horeab — CHANGES_REQUESTED** [review]
remove

**Comment by knonomura** [comment]
I'll merge this pull request soon.

NOTE: 
It supports only addBatch() without argument, but doesn't support addBatch(sql) with argument.

**Pull request merged**
